# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnimeList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimeList
pod 'DropDown'

  target 'AnimeListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnimeListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
